version: '2'

services:
  c-sgx:
    image: enclaive/c-sgx
    container_name: "c-sgx"
    privileged: true
    build:
      context: .
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"

  c-nosgx:
    image: enclaive/c-sgx
    container_name: "c-nosgx"
    privileged: true
    build:
      context: .
    entrypoint: ""
    command: "/app/app"
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"

